#!/bin/bash

options="Shutdown\nReboot\nLock\nLogout"
choice=$(echo -e "$options" | wofi --dmenu --width 200 --height 150 --prompt "Power")

case "$choice" in
  Shutdown) systemctl poweroff ;;
  Reboot) systemctl reboot ;;
  Lock) swaylock ;;
  Logout) swaymsg exit ;;
esac

